teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.13
    scale_linear_turbo:
      x: 0.26

    axis_angular:  # Right thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 0.91
    scale_angular_turbo:
      yaw: 1.82

    enable_button: 4  # Left button (LB)
    enable_turbo_button: 5  # Right button (RB)